### ISSUE TITLE
Implement TWAP oracle for AAVE

### ISSUE THREAD

**Issue by lajarre** [butterdao/molten#11]
Gov token = AAVE.

Deposit token = DAI.

**Comment by acemasterjb** [comment]
## Scenario where Uni V3 oracle is used

In the Uni V3 Oracle it is possible to chain two price queries to get the AAVE/DAI rate, by first getting the ETH/DAI price and using that output to get the AAVE/ETH amount.

`AAVE_ETH_price(ETH_DAI_price(x)) = AAVE_DAI_price` | `x` is the DAI amount inputted.

Whilst there is a DAI/AAVE pool on v3, liquidity is [just about non-existent](https://info.uniswap.org/#/pools/0xb20ed18ee19747c0811d57d38b7ab3d71e44c191). Making it a bit risky to get a price value from. Utilising this "oracle price chain" will give a more reliable price value.

The obvious caveat being the gas costs for conducting two price queries (16050 wei/call on avg based on 3 calls in `forge test`). 

## Scenario where Uni V2 oracle is used*

There is a DAI/AAVE pool on v2 with more liquidity, [but still not much](https://v2.info.uniswap.org/pair/0x38e12fdd8dc51e48830863151e1afa7799e6fe97).

\* also the V2 oracle isn't tested yet

**Comment by acemasterjb** [comment]
Oracle codebase has been moved to https://github.com/butterymoney/molten-oracle.

A plan should be discussed on how to integrate molten with the Oracle Consulter library.
