### ISSUE TITLE
Infinite `mTokens` claiming

### ISSUE THREAD

**Issue by acemasterjb** [butterdao/molten#22]
## Summary
The `claimMTokens` logic does not update the `mToken` allowance after a funder calls the function. Allowing infinite claiming.

## Details
Because `deposited[msg.sender]` is not updated in this function, any time after `exchange` is called funders can call `claimMTokens` until `mToken.transfer` reverts.

## Possible Solution

Update `deposited[msg.sender]` to `0` and change the `voteForLiquidation` functions to use the `mToken` balance for vote aggregation.

Then `unanimousLiquidationVote` needs to be updated to match the total circulating supply of `mTokens` instead of `depositToken`.

**Comment by acemasterjb** [comment]
Actually, a simpler solution would be to
```solidity
require(mTokensClaimed[msg.sender] == false)
```

**Comment by lajarre** [comment]
Good catch.
